### ISSUE TITLE
User

### ISSUE THREAD

**Issue by udaraKavishka** [TrackNGo/backend#4]
1. **User Profile and Preferences API**

Description: API for managing user and preferences.
**Sub-tasks:**
- [ ] Update profile information and notification settings.

2. **Route and Fare Information API**

Description: API to fetch route details and fare estimates.
**Sub-tasks:**
- [ ] Fetch routes, fare estimates, and schedules based on user input.

3. **Notification Management API**

Description: Handle user alerts for delays, fare changes, etc.
**Sub-tasks:**
- [ ] Create endpoint for sending and managing push notifications.
